# Generated by Django 2.0.4 on 2018-04-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DT', 'Daily Task'), ('WT', 'Weekly Task'), ('V', 'Verified'), ('D', 'Done')], default='Check Status', max_length=20)),
                ('name', models.CharField(default='ScrumStatus', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('task', models.TextField()),
                ('task_id', models.IntegerField(default=0)),
                ('moved_by', models.CharField(default='No Movement', max_length=60)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okoroscrumy.GoalStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.EmailField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('OW', 'Owner'), ('AD', 'Admin'), ('QA', 'Quality Analyst'), ('DE', 'Developer')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okoroscrumy.ScrumyUser'),
        ),
    ]
