# Generated by Django 2.0.4 on 2018-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okoroscrumy', '0002_auto_20180428_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('DT', 'Daily Task'), ('WT', 'Weekly Task'), ('V', 'Verified'), ('D', 'Done')], max_length=2),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(max_length=60),
        ),
    ]
